services:
  - type: web
    name: ai-feedback-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host=0.0.0.0 --port=10000"
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyBuQGv_w4XJMahtcfivi1ovhXdJcnWPcAc
    autoDeploy: true
    repo: https://github.com/Cubix33/RENDER
    branch: main
    rootDir: backend

  - type: static
    name: ai-feedback-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    autoDeploy: true
    repo: https://github.com/Cubix33/RENDER
    branch: main
    rootDir: frontend

